apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-kafka-adapter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-kafka-adapter.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.environment.KAFKA_SSL_CLIENT_KEY_PASS }}
  KAFKA_SSL_CLIENT_KEY_PASS: {{ .Values.environment.KAFKA_SSL_CLIENT_KEY_PASS | b64enc }}
{{- end }}{{- if .Values.environment.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_USERNAME: {{ .Values.environment.BASIC_AUTH_USERNAME | b64enc }}
{{- end }}{{- if .Values.environment.BASIC_AUTH_PASSWORD }}
  BASIC_AUTH_PASSWORD: {{ .Values.environment.BASIC_AUTH_PASSWORD | b64enc }}
{{- end }}
---
{{- if .Values.KAFKA_SSL_CLIENT_CERT }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-kafka-adapter.fullname" . }}-ssl-client-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-kafka-adapter.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.environment.KAFKA_SSL_CLIENT_CERT_FILE | default "/ssl_client_cert.pem" | base }}: {{ .Values.KAFKA_SSL_CLIENT_CERT | b64enc }}
---
{{- end }}
{{- if .Values.KAFKA_SSL_CLIENT_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-kafka-adapter.fullname" . }}-ssl-client-key
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-kafka-adapter.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.environment.KAFKA_SSL_CLIENT_KEY_FILE | default "/ssl_client_key.pem" | base }}: {{ .Values.KAFKA_SSL_CLIENT_KEY | b64enc }}
---
{{- end }}
{{- if .Values.KAFKA_SSL_CA_CERT }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-kafka-adapter.fullname" . }}-ssl-ca-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-kafka-adapter.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.environment.KAFKA_SSL_CA_CERT_FILE | default "/ssl_ca_cert.pem"  | base  }}: {{ .Values.KAFKA_SSL_CA_CERT | b64enc }}
---
{{- end }}
