{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-kafka-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-kafka-adapter.labels" . | indent 4 }}
{{- end -}}
